In [11]:
import pandas as pd
# Load the dataset
data = pd.read_csv('daily_data.csv')

# Display the first few rows of the dataset
data.head(20)

,day_id,city_id,temperature_celsius,condition_text,wind_kph,wind_degree,pressure_mb,precip_mm,humidity,cloud,feels_like_celsius,visibility_km,uv_index,gust_kph,air_quality_us-epa-index,sunrise,sunset
0,D0001,C001,27.0,NaN,6.1,210,1006.0,0.0,54,75,28.0,10.0,6.0,11.9,2,06:04 AM,07:19 PM
1,D0002,C001,22.0,NaN,6.1,170,1006.0,0.0,73,75,24.5,10.0,1.0,23.4,1,06:05 AM,07:18 PM
2,D0003,C001,20.0,Light Rain with Thunder,3.6,10,1011.0,4.5,100,75,20.0,10.0,1.0,12.6,1,06:05 AM,07:18 PM
3,D0004,C001,17.0,Clear and Sunny,6.1,150,1018.0,0.0,88,0,17.0,10.0,1.0,11.2,1,06:06 AM,07:16 PM
4,D0005,C001,18.0,NaN,3.6,92,1019.0,0.0,94,0,18.0,10.0,1.0,9.0,1,06:07 AM,07:15 PM
5,D0006,C001,20.0,NaN,3.6,96,1019.0,0.0,88,0,20.0,10.0,1.0,11.2,1,06:07 AM,07:13 PM
6,D0007,C001,21.0,Partly Cloudy,4.0,310,1015.0,0.0,100,50,21.0,10.0,1.0,15.1,2,06:08 AM,07:11 PM
7,D0008,C001,21.0,NaN,20.2,330,1011.0,0.0,53,75,21.0,10.0,1.0,17.3,1,06:09 AM,07:10 PM
8,D0009,C001,23.0,NaN,3.6,63,1013.0,0.0,47,75,24.8,10.0,1.0,20.5,1,06:10 AM,07:08 PM
9,D0010,C001,24.0,NaN,15.1,330,1014.0,0.0,54,75,25.3,10.0,1.0,9.7,1,06:11 AM,07:06 PM
10,D0011,C001,23.0,NaN,6.8,320,1014.0,0.0,57,0,24.8,10.0,1.0,18.7,1,06:12 AM,07:04 PM
11,D0012,C001,19.0,NaN,3.6,79,1014.0,0.0,73,0,19.0,10.0,1.0,18.0,1,06:13 AM,07:03 PM
12,D0013,C001,18.0,NaN,3.6,74,1015.0,0.0,83,0,18.0,10.0,1.0,14.4,1,06:14 AM,07:01 PM
13,D0014,C001,17.0,NaN,3.6,75,1015.0,0.0,88,0,17.0,10.0,1.0,14.4,1,06:15 AM,06:59 PM
14,D0015,C001,17.0,NaN,3.6,98,1014.0,0.0,94,0,17.0,10.0,1.0,9.7,1,06:16 AM,06:58 PM
15,D0016,C001,17.0,NaN,6.1,140,1017.0,0.0,88,0,17.0,10.0,1.0,7.6,2,06:17 AM,06:56 PM
16,D0017,C001,29.0,NaN,15.1,340,1016.0,0.0,45,50,27.9,10.0,7.0,8.3,2,06:19 AM,06:52 PM
17,D0018,C001,19.0,NaN,3.6,86,1017.0,0.0,88,0,19.0,10.0,1.0,6.8,2,06:19 AM,06:52 PM
18,D0019,C001,19.0,Clear and Sunny,3.6,64,1017.0,0.0,88,0,19.0,10.0,1.0,8.3,3,06:20 AM,06:51 PM
19,D0020,C001,19.0,NaN,3.6,10,1018.0,0.0,94,100,19.0,10.0,1.0,5.4,2,06:21 AM,06:49 PM

Encode Target Variable

Encode city_id

In [12]:
import re

# Function to extract numeric part from city_id
def extract_numeric_part(city_id):
    numeric_part = re.search(r'\d+', city_id)
    if numeric_part:
        return int(numeric_part.group())
    else:
        return None  # Handle cases where numeric part is not found or is invalid

# Apply the function to extract numeric part from city_id
data['city_id_numeric'] = data['city_id'].apply(extract_numeric_part)

In [13]:
data.head(20)

,day_id,city_id,temperature_celsius,condition_text,wind_kph,wind_degree,pressure_mb,precip_mm,humidity,cloud,feels_like_celsius,visibility_km,uv_index,gust_kph,air_quality_us-epa-index,sunrise,sunset,city_id_numeric
0,D0001,C001,27.0,NaN,6.1,210,1006.0,0.0,54,75,28.0,10.0,6.0,11.9,2,06:04 AM,07:19 PM,1
1,D0002,C001,22.0,NaN,6.1,170,1006.0,0.0,73,75,24.5,10.0,1.0,23.4,1,06:05 AM,07:18 PM,1
2,D0003,C001,20.0,Light Rain with Thunder,3.6,10,1011.0,4.5,100,75,20.0,10.0,1.0,12.6,1,06:05 AM,07:18 PM,1
3,D0004,C001,17.0,Clear and Sunny,6.1,150,1018.0,0.0,88,0,17.0,10.0,1.0,11.2,1,06:06 AM,07:16 PM,1
4,D0005,C001,18.0,NaN,3.6,92,1019.0,0.0,94,0,18.0,10.0,1.0,9.0,1,06:07 AM,07:15 PM,1
5,D0006,C001,20.0,NaN,3.6,96,1019.0,0.0,88,0,20.0,10.0,1.0,11.2,1,06:07 AM,07:13 PM,1
6,D0007,C001,21.0,Partly Cloudy,4.0,310,1015.0,0.0,100,50,21.0,10.0,1.0,15.1,2,06:08 AM,07:11 PM,1
7,D0008,C001,21.0,NaN,20.2,330,1011.0,0.0,53,75,21.0,10.0,1.0,17.3,1,06:09 AM,07:10 PM,1
8,D0009,C001,23.0,NaN,3.6,63,1013.0,0.0,47,75,24.8,10.0,1.0,20.5,1,06:10 AM,07:08 PM,1
9,D0010,C001,24.0,NaN,15.1,330,1014.0,0.0,54,75,25.3,10.0,1.0,9.7,1,06:11 AM,07:06 PM,1
10,D0011,C001,23.0,NaN,6.8,320,1014.0,0.0,57,0,24.8,10.0,1.0,18.7,1,06:12 AM,07:04 PM,1
11,D0012,C001,19.0,NaN,3.6,79,1014.0,0.0,73,0,19.0,10.0,1.0,18.0,1,06:13 AM,07:03 PM,1
12,D0013,C001,18.0,NaN,3.6,74,1015.0,0.0,83,0,18.0,10.0,1.0,14.4,1,06:14 AM,07:01 PM,1
13,D0014,C001,17.0,NaN,3.6,75,1015.0,0.0,88,0,17.0,10.0,1.0,14.4,1,06:15 AM,06:59 PM,1
14,D0015,C001,17.0,NaN,3.6,98,1014.0,0.0,94,0,17.0,10.0,1.0,9.7,1,06:16 AM,06:58 PM,1
15,D0016,C001,17.0,NaN,6.1,140,1017.0,0.0,88,0,17.0,10.0,1.0,7.6,2,06:17 AM,06:56 PM,1
16,D0017,C001,29.0,NaN,15.1,340,1016.0,0.0,45,50,27.9,10.0,7.0,8.3,2,06:19 AM,06:52 PM,1
17,D0018,C001,19.0,NaN,3.6,86,1017.0,0.0,88,0,19.0,10.0,1.0,6.8,2,06:19 AM,06:52 PM,1
18,D0019,C001,19.0,Clear and Sunny,3.6,64,1017.0,0.0,88,0,19.0,10.0,1.0,8.3,3,06:20 AM,06:51 PM,1
19,D0020,C001,19.0,NaN,3.6,10,1018.0,0.0,94,100,19.0,10.0,1.0,5.4,2,06:21 AM,06:49 PM,1

Encode sunset,sunrise columns

In [14]:
def time_to_minutes(time_str):
    # Example: time_str = '2.30AM'
    time_str = time_str.strip().upper()  # Convert to uppercase and strip whitespace
    
    if 'AM' in time_str:
        hours, minutes = map(int, time_str.replace('AM', '').split(':'))
        if hours == 12:
            hours = 0  # Midnight case
    elif 'PM' in time_str:
        hours, minutes = map(int, time_str.replace('PM', '').split(':'))
        if hours != 12:
            hours += 12  # Convert PM hours to 24-hour format
    else:
        return None  # Handle invalid cases
    
    return hours * 60 + minutes  # Convert to minutes past midnight

In [15]:
# Apply the function to encode sunrise and sunset
data['sunset_minutes'] = data['sunset'].apply(time_to_minutes)
data['sunrise_minutes'] = data['sunrise'].apply(time_to_minutes)


# Display the updated dataframe
print(data[['sunrise', 'sunrise_minutes', 'sunset', 'sunset_minutes']].head())

    sunrise  sunrise_minutes    sunset  sunset_minutes
0  06:04 AM              364  07:19 PM            1159
1  06:05 AM              365  07:18 PM            1158
2  06:05 AM              365  07:18 PM            1158
3  06:06 AM              366  07:16 PM            1156
4  06:07 AM              367  07:15 PM            1155

In [16]:
data.head()

,day_id,city_id,temperature_celsius,condition_text,wind_kph,wind_degree,pressure_mb,precip_mm,humidity,cloud,feels_like_celsius,visibility_km,uv_index,gust_kph,air_quality_us-epa-index,sunrise,sunset,city_id_numeric,sunset_minutes,sunrise_minutes
0,D0001,C001,27.0,NaN,6.1,210,1006.0,0.0,54,75,28.0,10.0,6.0,11.9,2,06:04 AM,07:19 PM,1,1159,364
1,D0002,C001,22.0,NaN,6.1,170,1006.0,0.0,73,75,24.5,10.0,1.0,23.4,1,06:05 AM,07:18 PM,1,1158,365
2,D0003,C001,20.0,Light Rain with Thunder,3.6,10,1011.0,4.5,100,75,20.0,10.0,1.0,12.6,1,06:05 AM,07:18 PM,1,1158,365
3,D0004,C001,17.0,Clear and Sunny,6.1,150,1018.0,0.0,88,0,17.0,10.0,1.0,11.2,1,06:06 AM,07:16 PM,1,1156,366
4,D0005,C001,18.0,NaN,3.6,92,1019.0,0.0,94,0,18.0,10.0,1.0,9.0,1,06:07 AM,07:15 PM,1,1155,367

In [17]:
data.drop(['sunset', 'sunrise', 'city_id'], axis=1, inplace=True)

Split Known and Unknown

In [18]:
data_known = data.dropna(subset=['condition_text'])

# Data with unknown target values
data_unknown = data[data['condition_text'].isnull()]

In [19]:
data_known.head(20)

,day_id,temperature_celsius,condition_text,wind_kph,wind_degree,pressure_mb,precip_mm,humidity,cloud,feels_like_celsius,visibility_km,uv_index,gust_kph,air_quality_us-epa-index,city_id_numeric,sunset_minutes,sunrise_minutes
2,D0003,20.0,Light Rain with Thunder,3.6,10,1011.0,4.50,100,75,20.0,10.0,1.0,12.6,1,1,1158,365
3,D0004,17.0,Clear and Sunny,6.1,150,1018.0,0.00,88,0,17.0,10.0,1.0,11.2,1,1,1156,366
6,D0007,21.0,Partly Cloudy,4.0,310,1015.0,0.00,100,50,21.0,10.0,1.0,15.1,2,1,1151,368
18,D0019,19.0,Clear and Sunny,3.6,64,1017.0,0.00,88,0,19.0,10.0,1.0,8.3,3,1,1131,380
27,D0028,19.0,Partly Cloudy,3.6,83,1010.0,0.00,73,25,19.0,10.0,1.0,8.3,1,2,1160,377
34,D0035,25.0,Partly Cloudy,6.1,70,1015.0,0.00,83,25,27.0,10.0,1.0,17.3,1,2,1151,381
41,D0042,25.0,Light Rain with Thunder,3.6,141,1016.0,0.00,83,50,26.3,8.0,1.0,14.4,1,2,1140,387
78,D0079,29.0,Light Precipitation,15.1,90,1015.0,0.30,79,75,34.0,10.0,1.0,37.4,1,4,1103,353
80,D0081,29.0,Cloudy and Overcast,15.1,100,1015.0,0.10,79,50,34.1,10.0,1.0,33.5,1,4,1102,354
86,D0087,27.0,Cloudy and Overcast,6.1,100,1015.0,0.10,79,62,29.9,10.0,1.0,31.7,1,4,1098,354
98,D0099,29.0,Partly Cloudy,9.0,70,1012.0,0.24,70,25,33.3,10.0,6.0,22.2,1,4,1088,356
102,D0103,29.0,Cloudy and Overcast,9.0,100,1012.0,0.02,75,50,33.4,10.0,6.0,30.4,1,4,1084,356
105,D0106,11.0,Clear and Sunny,15.1,80,1019.0,0.00,82,0,9.9,10.0,1.0,18.0,1,5,1115,437
110,D0111,11.0,Cloudy and Overcast,15.1,170,1013.0,0.20,94,100,9.2,10.0,1.0,21.6,1,5,1117,431
113,D0114,12.0,Clear and Sunny,24.1,120,1020.0,0.00,77,0,9.9,10.0,1.0,32.0,1,5,1120,427
124,D0125,16.0,Clear and Sunny,28.1,160,1011.0,0.04,51,0,16.0,10.0,1.0,33.3,1,5,1127,411
126,D0127,15.0,Partly Cloudy,28.1,120,1019.0,0.00,77,75,13.8,10.0,1.0,25.9,1,5,1129,409
127,D0128,16.0,Light Precipitation,20.2,120,1014.0,0.08,94,100,16.0,2.5,1.0,25.6,1,5,1129,407
133,D0134,24.0,Clear and Sunny,9.0,40,1015.0,0.00,36,0,25.2,10.0,1.0,22.7,1,6,1176,388
140,D0141,25.0,Clear and Sunny,19.1,360,1012.0,0.00,39,0,26.1,10.0,1.0,18.4,1,6,1165,395

Encode target variable

In [20]:
# from sklearn.preprocessing import LabelEncoder

# # Define weather conditions
# weather_conditions = [
#     'Clear and Sunny', 'Partly Cloudy', 'Light Precipitation', 'Cloudy and Overcast',
#     'Mist or Fog', 'Rain Showers', 'Light Rain with Thunder', 'Thunderstorms', 'Moderate to Heavy Rain'
# ]

# # Create a LabelEncoder instance
# label_encoder = LabelEncoder()

# # Fit the label encoder with the weather conditions
# label_encoder.fit(weather_conditions)

# # Encode the condition_text column
# data_known['condition_text'] = label_encoder.transform(data_known['condition_text'].astype(str))

weather_conditions = {
    'Clear and Sunny': 0,
    'Partly Cloudy': 1,
    'Light Precipitation': 2,
    'Cloudy and Overcast': 3,
    'Mist or Fog': 4,
    'Rain Showers': 5,
    'Light Rain with Thunder': 6,
    'Thunderstorms': 7,
    'Moderate to Heavy Rain': 8
}

# Encode the condition_text column manually using the dictionary
data_known['condition_text'] = data_known['condition_text'].map(weather_conditions)

# Print the encoded DataFrame to verify
print(data_known)

     day_id  temperature_celsius  condition_text  wind_kph  wind_degree  \
2     D0003                 20.0               6       3.6           10
3     D0004                 17.0               0       6.1          150
6     D0007                 21.0               1       4.0          310
18    D0019                 19.0               0       3.6           64
27    D0028                 19.0               1       3.6           83
...     ...                  ...             ...       ...          ...
2838  D2839                 27.0               1      19.1           90
2863  D2864                 21.4               2       3.6          178
2873  D2874                 16.9               0      16.6           68
2886  D2887                 19.5               0       5.4           27
2888  D2889                 17.1               0      13.3           61

      pressure_mb  precip_mm  humidity  cloud  feels_like_celsius  \
2          1011.0       4.50       100     75                20.0
3          1018.0       0.00        88      0                17.0
6          1015.0       0.00       100     50                21.0
18         1017.0       0.00        88      0                19.0
27         1010.0       0.00        73     25                19.0
...           ...        ...       ...    ...                 ...
2838       1014.0       0.01        70     25                29.8
2863       1012.0       0.00        89     75                21.4
2873       1018.0       0.00        44      2                16.9
2886       1014.0       0.00        34      0                19.4
2888       1017.0       0.00        57      3                17.1

      visibility_km  uv_index  gust_kph  air_quality_us-epa-index  \
2              10.0       1.0      12.6                         1
3              10.0       1.0      11.2                         1
6              10.0       1.0      15.1                         2
18             10.0       1.0       8.3                         3
27             10.0       1.0       8.3                         1
...             ...       ...       ...                       ...
2838           10.0       6.0      45.6                         1
2863           10.0       6.0       6.6                         1
2873           10.0       1.0      27.0                         1
2886           10.0       1.0      11.2                         2
2888           10.0       1.0      22.2                         1

      city_id_numeric  sunset_minutes  sunrise_minutes
2                   1            1158              365
3                   1            1156              366
6                   1            1151              368
18                  1            1131              380
27                  2            1160              377
...               ...             ...              ...
2838              110            1063              339
2863              111            1105              377
2873              112            1069              362
2886              112            1071              351
2888              112            1071              349

[479 rows x 17 columns]

C:\Users\dulmi\AppData\Local\Temp\ipykernel_9376\3142754692.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_known['condition_text'] = data_known['condition_text'].map(weather_conditions)

In [21]:
data_known.head(100)

,day_id,temperature_celsius,condition_text,wind_kph,wind_degree,pressure_mb,precip_mm,humidity,cloud,feels_like_celsius,visibility_km,uv_index,gust_kph,air_quality_us-epa-index,city_id_numeric,sunset_minutes,sunrise_minutes
2,D0003,20.0,6,3.6,10,1011.0,4.5,100,75,20.0,10.0,1.0,12.6,1,1,1158,365
3,D0004,17.0,0,6.1,150,1018.0,0.0,88,0,17.0,10.0,1.0,11.2,1,1,1156,366
6,D0007,21.0,1,4.0,310,1015.0,0.0,100,50,21.0,10.0,1.0,15.1,2,1,1151,368
18,D0019,19.0,0,3.6,64,1017.0,0.0,88,0,19.0,10.0,1.0,8.3,3,1,1131,380
27,D0028,19.0,1,3.6,83,1010.0,0.0,73,25,19.0,10.0,1.0,8.3,1,2,1160,377
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
637,D0638,18.0,0,6.1,190,1018.0,0.0,73,0,18.0,10.0,1.0,4.7,3,25,1168,390
638,D0639,21.0,0,6.8,150,1013.0,0.0,69,0,21.0,10.0,1.0,9.4,2,25,1166,391
646,D0647,14.0,0,16.9,190,1015.0,0.0,77,0,13.4,10.0,1.0,21.9,1,25,1148,403
647,D0648,16.0,0,9.0,150,1011.0,0.0,72,0,16.0,10.0,1.0,12.9,1,25,1146,405
654,D0655,32.4,0,5.8,220,1005.0,0.0,57,8,37.4,10.0,1.0,11.5,2,26,1097,357

In [22]:
# Exclude 'day_id' from the dataframe
data_known_original= data_known

data_known = data_known.drop(columns=['day_id'])

# Calculate correlation matrix
correlation_matrix = data_known.corr()

# Correlation with condition_text
correlation_with_target = correlation_matrix['condition_text'].sort_values(ascending=False)

# Print correlation with condition_text
print("Correlation with condition_text:")
print(correlation_with_target)

Correlation with condition_text:
condition_text              1.000000
cloud                       0.464306
humidity                    0.365381
precip_mm                   0.271485
wind_kph                    0.105164
air_quality_us-epa-index    0.087676
feels_like_celsius          0.078689
wind_degree                 0.067241
temperature_celsius         0.062097
uv_index                    0.060961
gust_kph                    0.034067
city_id_numeric            -0.020687
sunrise_minutes            -0.051878
sunset_minutes             -0.072335
pressure_mb                -0.167261
visibility_km              -0.256183
Name: condition_text, dtype: float64

Handeling Missing Values

In [23]:
columns_with_missing = data_known.columns[data_known.isnull().any()]
print(columns_with_missing)

Index([], dtype='object')

Feature selection

In [24]:
# # Set a correlation threshold (this can be adjusted based on your dataset)
# correlation_threshold = 0.08

# # Select features with correlation above the threshold
# selected_features = correlation_with_target[correlation_with_target.abs() > correlation_threshold].index.tolist()

# # Remove the target variable from the list of selected features
# selected_features.remove('condition_text')

# print("Selected features based on correlation threshold:")
# print(selected_features)

In [25]:
from sklearn.feature_selection import mutual_info_classif
from sklearn.preprocessing import LabelEncoder

# Encode the target variable if it's categorical
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(data_known['condition_text'])

# Calculate mutual information between each feature and the target
mutual_info = mutual_info_classif(data_known.drop(columns=['condition_text']), y_encoded)

# Create a series with feature names and their MI scores
mutual_info_series = pd.Series(mutual_info, index=data_known.drop(columns=['condition_text']).columns)

# Sort the series in descending order
mutual_info_series = mutual_info_series.sort_values(ascending=False)

print("Mutual Information scores:")
print(mutual_info_series)

# Select top N features based on MI score
top_n_features = mutual_info_series.head(10).index.tolist()  # Adjust the number of features as needed

print("Top N selected features based on mutual information:")
print(top_n_features)

data_known= data_known_original

Mutual Information scores:
cloud                       0.819502
city_id_numeric             0.362385
humidity                    0.250616
visibility_km               0.236533
precip_mm                   0.164591
temperature_celsius         0.142164
feels_like_celsius          0.125098
sunset_minutes              0.097507
sunrise_minutes             0.084794
wind_degree                 0.070149
air_quality_us-epa-index    0.057949
pressure_mb                 0.052855
uv_index                    0.038384
gust_kph                    0.005621
wind_kph                    0.002487
dtype: float64
Top N selected features based on mutual information:
['cloud', 'city_id_numeric', 'humidity', 'visibility_km', 'precip_mm', 'temperature_celsius', 'feels_like_celsius', 'sunset_minutes', 'sunrise_minutes', 'wind_degree']

New Dataframe with selected features

In [26]:
# Select the features from data_known based on the chosen method
selected_features_based_on_correlation = correlation_with_target[correlation_with_target.abs() > 0.08].index.tolist()
selected_features_based_on_correlation.remove('condition_text')

# Or use the top N features based on mutual information
selected_features = top_n_features  # Or selected_features_based_on_correlation

# Create a new DataFrame with selected features and the target variable
data_selected = data_known[selected_features + ['condition_text'] +['day_id'] ]

data_selected_unknown=data_unknown[selected_features +['day_id'] ]

# Print the new DataFrame to verify
print(data_selected.head())

    cloud  city_id_numeric  humidity  visibility_km  precip_mm  \
2      75                1       100           10.0        4.5
3       0                1        88           10.0        0.0
6      50                1       100           10.0        0.0
18      0                1        88           10.0        0.0
27     25                2        73           10.0        0.0

    temperature_celsius  feels_like_celsius  sunset_minutes  sunrise_minutes  \
2                  20.0                20.0            1158              365
3                  17.0                17.0            1156              366
6                  21.0                21.0            1151              368
18                 19.0                19.0            1131              380
27                 19.0                19.0            1160              377

    wind_degree  condition_text day_id
2            10               6  D0003
3           150               0  D0004
6           310               1  D0007
18           64               0  D0019
27           83               1  D0028

In [27]:
data_selected_unknown.head(20)

,cloud,city_id_numeric,humidity,visibility_km,precip_mm,temperature_celsius,feels_like_celsius,sunset_minutes,sunrise_minutes,wind_degree,day_id
0,75,1,54,10.0,0.0,27.0,28.0,1159,364,210,D0001
1,75,1,73,10.0,0.0,22.0,24.5,1158,365,170,D0002
4,0,1,94,10.0,0.0,18.0,18.0,1155,367,92,D0005
5,0,1,88,10.0,0.0,20.0,20.0,1153,367,96,D0006
7,75,1,53,10.0,0.0,21.0,21.0,1150,369,330,D0008
8,75,1,47,10.0,0.0,23.0,24.8,1148,370,63,D0009
9,75,1,54,10.0,0.0,24.0,25.3,1146,371,330,D0010
10,0,1,57,10.0,0.0,23.0,24.8,1144,372,320,D0011
11,0,1,73,10.0,0.0,19.0,19.0,1143,373,79,D0012
12,0,1,83,10.0,0.0,18.0,18.0,1141,374,74,D0013
13,0,1,88,10.0,0.0,17.0,17.0,1139,375,75,D0014
14,0,1,94,10.0,0.0,17.0,17.0,1138,376,98,D0015
15,0,1,88,10.0,0.0,17.0,17.0,1136,377,140,D0016
16,50,1,45,10.0,0.0,29.0,27.9,1132,379,340,D0017
17,0,1,88,10.0,0.0,19.0,19.0,1132,379,86,D0018
19,100,1,94,10.0,0.0,19.0,19.0,1129,381,10,D0020
20,0,1,94,10.0,0.0,18.0,18.0,1127,382,75,D0021
21,0,1,83,10.0,0.0,20.0,20.0,1125,383,104,D0022
22,0,1,94,10.0,0.0,20.0,20.0,1124,384,70,D0023
23,75,1,83,10.0,0.0,21.0,21.0,1122,385,200,D0024

In [28]:
 
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
from sklearn.model_selection import   GridSearchCV
from sklearn.model_selection import train_test_split

# Assuming 'data_known' is your dataframe containing the known data
# X and y should already be defined as features and target variable


# Split data_known into features (X) and target variable (y)
X = data_selected.drop(columns=['condition_text','day_id'])  # Features
y = data_selected['condition_text']  # Target variable


# Split the data into training and testing sets (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Define the parameter grid
param_grid = {
    'n_estimators': [100, 200, 300],  # Number of trees in the forest
    'max_depth': [None, 10, 20, 30],  # Maximum depth of the trees
    'min_samples_split': [2, 5, 10],  # Minimum number of samples required to split an internal node
    'min_samples_leaf': [1, 2, 4]  # Minimum number of samples required to be at a leaf node
}

# Initialize the Random Forest Classifier
rf_classifier = RandomForestClassifier(random_state=42)

# Initialize GridSearchCV with the classifier and parameter grid
grid_search = GridSearchCV(estimator=rf_classifier, param_grid=param_grid, cv=5, scoring='accuracy', verbose=1, n_jobs=-1)

# Fit the grid search to the data
grid_search.fit(X_train, y_train)

# Print the best parameters and best score
print("Best Parameters:")
print(grid_search.best_params_)
print("Best CV Accuracy: {:.2f}".format(grid_search.best_score_))

# Evaluate the best model on the test set
best_rf = grid_search.best_estimator_
y_pred = best_rf.predict(X_test)

# Print accuracy and classification report
accuracy = accuracy_score(y_test, y_pred)
print(f"Test Accuracy: {accuracy:.2f}")
print("Classification Report:")
print(classification_report(y_test, y_pred))

Fitting 5 folds for each of 108 candidates, totalling 540 fits
Best Parameters:
{'max_depth': 10, 'min_samples_leaf': 2, 'min_samples_split': 10, 'n_estimators': 200}
Best CV Accuracy: 0.73
Test Accuracy: 0.70
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        22
           1       0.61      0.88      0.72        26
           2       0.64      0.58      0.61        12
           3       0.54      0.58      0.56        12
           4       0.78      0.88      0.82         8
           5       0.50      0.20      0.29         5
           6       0.00      0.00      0.00         5
           7       0.00      0.00      0.00         2
           8       0.00      0.00      0.00         4

    accuracy                           0.70        96
   macro avg       0.45      0.46      0.44        96
weighted avg       0.63      0.70      0.65        96

c:\Users\dulmi\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1497: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\dulmi\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1497: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\dulmi\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1497: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [29]:
data_selected_unknown.head()

,cloud,city_id_numeric,humidity,visibility_km,precip_mm,temperature_celsius,feels_like_celsius,sunset_minutes,sunrise_minutes,wind_degree,day_id
0,75,1,54,10.0,0.0,27.0,28.0,1159,364,210,D0001
1,75,1,73,10.0,0.0,22.0,24.5,1158,365,170,D0002
4,0,1,94,10.0,0.0,18.0,18.0,1155,367,92,D0005
5,0,1,88,10.0,0.0,20.0,20.0,1153,367,96,D0006
7,75,1,53,10.0,0.0,21.0,21.0,1150,369,330,D0008

In [30]:
# Predict condition_text for the data_unknown dataframe
X_unknown = data_selected_unknown.drop(columns=['day_id'])
data_selected_unknown['condition_text'] = best_rf.predict(X_unknown)

# Combine data_known and data_unknown
combined_data = pd.concat([data_selected_unknown, data_selected], ignore_index=True)

# Create the submission dataframe with day_id and condition_text
submission = combined_data[['day_id', 'condition_text']]

 submission.to_csv('submission.csv', index=False)

C:\Users\dulmi\AppData\Local\Temp\ipykernel_9376\2067870625.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_selected_unknown['condition_text'] = best_rf.predict(X_unknown)